// src/components/Header.tsx
import React from "react";

const Header = () => {
  return (
    <header className="header">
      <a href="#" className="logo">
        Portfolio
      </a>
      <i className="bx bx-menu" id="menu-icon"></i>
      <nav className="navbar">
        <a href="#home">Home</a>
        <a href="#about">About</a>
        <a href="#service">Services</a>
        <a href="#portfolio">Portfolio</a>
        <a href="#contact">Contact</a>
      </nav>
    </header>
  );
};

export default Header;

// src/components/Header.vue
<template lang="ts">
<header class="header">
  <a href="#" class="logo">
    Portfolio
  </a>
  <i class="bx bx-menu" id="menu-icon"></i>
  <nav class="navbar">
    <a href="#home">Home</a>
    <a href="#about">About</a>
    <a href="#service">Services</a>
    <a href="#portfolio">Portfolio</a>
    <a href="#contact">Contact</a>
  </nav>
</header>;
</template>
<script setup lang="ts"></script>
<style lang="ts"></style>
